// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"OnlineAvatar","status":true,"description":"Firebaseを使ってプレイヤーをオンライン同期します。","parameters":{"apiKey":"AIzaSyDpPbEK2W5KkY4AediAm5GpwFEzG7EzKcw","authDomain":"nana-ac343.firebaseapp.com","databaseURL":"https://nana-ac343.firebaseio.com","avatarEvent":"1","syncSwitchStart":"11","syncSwitchEnd":"100","syncVariableStart":"11","syncVariableEnd":"100"}},
{"name":"CharacterPopupDamage","status":true,"description":"キャラクターのダメージポッププラグイン","parameters":{"効果音演奏":"ON","X座標補正":"0","Y座標補正":"0","HP自動ポップアップ":"ON","MP自動ポップアップ":"ON","TP自動ポップアップ":"ON","増加自動ポップアップ":"ON","減少自動ポップアップ":"ON","MPダメージ音":""}},
{"name":"AdjustPictureGraphical","status":true,"description":"ピクチャのグラフィカルな位置調整プラグイン","parameters":{}},
{"name":"DTextPicture","status":true,"description":"動的文字列ピクチャ生成プラグイン","parameters":{}},
{"name":"DWindow","status":true,"description":"動的ウィンドウ生成プラグイン","parameters":{"X座標の変数番号":"1","Y座標の変数番号":"2","横幅の変数番号":"3","高さの変数番号":"4"}},
{"name":"TMNamePop","status":true,"description":"イベントの頭上に文字列を表示する機能を追加します。","parameters":{"backOpacity":"96","fontSize":"20","fontOutlineWidth":"4","fontOutlineColor":"rgba(0, 0, 0, 0.5)","width":"160","useRoundRect":"0","roundRectRadius":"6"}}
];
