// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MadeWithMv","status":false,"description":"メイン画面へ進む前に、\"Made with MV\"のスプラッシュ画面もしくはカスタマイズされたスプラッシュ画面を表示します。","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"TMGreedShop","status":true,"description":"お金以外にアイテムも要求されるショップ機能を追加します。","parameters":{"materialWindowWidth":"408","materialMax":"12","greedCommand":"組み合わせる"}},
{"name":"dsEquipmentSkillLearning","status":true,"description":"装備に設定されたスキルを習得するプラグイン ver1.06","parameters":{"Lp":"KILL数","Basic Reward Lp":"1","Reward Lp Text":"%1体の魔物をKILL！","Show Reward Lp Text":"true","Learning Skill Text":"%1は%2を覚えた！","Usable Equipment Skill":"true","Show Lp Gauge":"true","Show Lp Value":"true","Lp Value Font Size":"18","Lp Aftermath Enable":"true","Lp Aftermath Caption":"KILL獲得","Lp Aftermath Format":"+%1\\c[4]%2\\c[0]","Lp Aftermath Earned":"KILL数"}},
{"name":"TitleCommandPosition","status":true,"description":"タイトルコマンドウィンドウの位置を変更します。","parameters":{"Offset X":"250","Offset Y":"-30","Width":"240","Background":"2"}},
{"name":"TinyGetInfoWnd","status":true,"description":"マップ上でアイテムの入手/消失を小さなウィンドウで表示します。","parameters":{"Event Command Switch":"22","Y position type":"1","textGainItem":"%1入手！","textLoseItem":"%1消失……。","SE filename":"Item3","SE volume":"90","SE pitch":"100"}},
{"name":"Torigoya_SameEquipType","status":true,"description":"装備タイプ名が同じならば、同じ種別のアイテムを装備できるようにします","parameters":{}},
{"name":"TemplateEvent","status":true,"description":"テンプレートイベントプラグイン","parameters":{"テンプレートマップID":"1","イベントIDを維持":"OFF","グラフィック置換":"OFF"}},
{"name":"TYA_BattleCommandCustom","status":true,"description":"パーティ・アクターコマンドを横長にします。\r\nそれに合わせてバトルステータスの表示も変更します。","parameters":{"partyCommandWindowSet":"2, 1","actorCommandWindowSet":"4, 1","statusWindowRows":"2","stateIconWidth":"6","statusWindowCustom":"1","coverColor1":"0, 0, 0, 0.5","coverColor2":"255, 255, 255, 0.5"}},
{"name":"AltMenuScreen_ky","status":true,"description":"メニュー画面のレイアウトを変更します。","parameters":{"maxColsMenu":"2"}},
{"name":"TYA_EnemyHPGauge","status":true,"description":"敵ターゲットウィンドウにＨＰゲージを表示させます。\r\n特定の敵のゲージを非表示にすることもできます。","parameters":{}},
{"name":"MKR_LevelUpMessageEx","status":true,"description":"(v1.0.2) レベルアップ時にステータスの変化を\nウィンドウに表示します。","parameters":{"Default_Status_Message":"ON","Default_Visible_Hp":"ON","Default_Visible_Mp":"ON","Default_Visible_Atk":"ON","Default_Visible_Grd":"ON","Default_Visible_mAtk":"ON","Default_Visible_mGrd":"ON","Default_Visible_Spd":"ON","Default_Visible_Luk":"ON"}},
{"name":"AdjustPictureGraphical","status":true,"description":"ピクチャのグラフィカルな位置調整プラグイン","parameters":{}},
{"name":"MKR_PlayerMoveForbid","status":true,"description":"(v1.0.1) 指定された番号のスイッチがONの間、\nプレイヤー操作によるキャラの移動を禁止します。","parameters":{"Default_Move_Flag":"10"}},
{"name":"OuterSelfSwitch","status":true,"description":"他のイベントのセルフスイッチを操作します。","parameters":{}},
{"name":"YEP_GabWindow","status":true,"description":"v1.03a \"Gab Window\"はメッセージウィンドウ無しで画面上におしゃべりを表示できるプラグインです。","parameters":{"---一般---":"","Gab Font Name":"GameFont","Gab Font Size":"22","Character X Pos":"36","Character Y Pos":"60","Base Wait Time":"90","Time Per Character":"4","Fade Rate":"16","Anti-Repeat":"true","---マップ時---":"","Map Y Location":"152","Map Dim Color 1":"rgba(0, 0, 0, 0.6)","Map Dim Color 2":"rgba(0, 0, 0, 0.3)","---戦闘---":"","Battle Y Location":"108","Battle Dim Color 1":"rgba(0, 0, 0, 0.6)","Battle Dim Color 2":"rgba(0, 0, 0, 0)"}},
{"name":"DWindow","status":true,"description":"動的ウィンドウ生成プラグイン","parameters":{"X座標の変数番号":"1","Y座標の変数番号":"2","横幅の変数番号":"3","高さの変数番号":"4","最前面に表示":"OFF","ピクチャに含める":"0"}},
{"name":"MPP_ChoiceEX","status":true,"description":"【ver.3.3】選択肢の機能拡張","parameters":{"maxPageRow":"6"}},
{"name":"DynamicDatabase","status":true,"description":"動的データベース構築プラグイン","parameters":{}},
{"name":"TMAnimeLight","status":true,"description":"イベントにアニメーション付きの明かりを表示します。","parameters":{"range":"0.1","defaultZ":"4","frames":"30"}},
{"name":"DTextPicture","status":true,"description":"動的文字列ピクチャ生成プラグイン","parameters":{}}
];
