// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"OnlineAvatar","status":true,"description":"Firebaseを使ってプレイヤーをオンライン同期します。","parameters":{"apiKey":"AIzaSyDpPbEK2W5KkY4AediAm5GpwFEzG7EzKcw","authDomain":"nana-ac343.firebaseapp.com","databaseURL":"https://nana-ac343.firebaseio.com","avatarEvent":"1","syncSwitchStart":"11","syncSwitchEnd":"100","syncVariableStart":"11","syncVariableEnd":"100"}}
];
